# -*- coding: utf-8 -*-
"""2.6 stage 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RLmx7xWHIqwwvml9rTz5jJgXv3o97HRW
"""

!pip install pandas
!pip install seaborn

import pandas as pd
import seaborn as sns

#import data set
data = "https://gist.githubusercontent.com/stephenturner/806e31fce55a8b7175af/raw/1a507c4c3f9f1baaa3a69187223ff3d3050628d4/results.txt"
df = pd.read_csv(data, delim_whitespace= True)
print(df)

#generate volcano plot y-axis= p-value, x-axis= log2foldchange
sns.scatterplot(df, x="log2FoldChange", y="pvalue")

#upregulated genes: genes with log2fc > 1 and pvalue < 0.001
upregulated_genes = df.loc[(df["log2FoldChange"] > 1) & (df["pvalue"] < 0.001)]
print(upregulated_genes)

# Downregulated gene: genes with log2fc < -1 and pvalue > 0.001
downregulated_gene = df.loc[(df["log2FoldChange"] <-1) & (df["pvalue"] >0.001)]

# 5 upregulated gene
upregulated_genes.iloc[0:5]